### ISSUE TITLE
doesn't remove spaces for odt exporting

### ISSUE THREAD

**Issue by QiangF** [tumashu/org-chinese-utils#1]
Hello Sir,
I am using org-odt-export-to-odt to do the converting.
Thank you!

**Comment by tumashu** [comment]
的确，这个功能只支持 ox-html 相关的，odt不支持

**Comment by QiangF** [comment]
能不能先转成html然后再转成odt，相关的代码是

    (defun org-export-as-odt (arg &optional hidden ext-plist
                    to-buffer body-only pub-dir)
    (interactive "P")
    (org-odt-cleanup-xml-buffers
    (org-lparse (or org-export-odt-preferred-output-format "odt")
            "odt" arg hidden ext-plist to-buffer body-only pub-dir)))

**Comment by tumashu** [comment]
不知道，估计不行， ox-odt 和 ox-html 好像没有什么交集

**Comment by QiangF** [comment]
能不能用 org-chinese-utils-clean-useless-space 过滤一下生成一个临时的buffer送给 org-lparse？ 实在不行我就只能用visual-line-mode了。

**Comment by tumashu** [comment]
也许可能，你可以试试
```

(defun org-chinese-utils-clean-useless-space (text backend info)
  "将 org file export 为 HTML 时，删除中文之间不必要的空格。"
  (when (or (org-export-derived-backend-p backend 'html)
            (eq backend 'odt))
    (let ((regexp "[[:multibyte:]]")
          (string text))
      ;; org默认将一个换行符转换为空格，但中文不需要这个空格，删除。
      (setq string
            (replace-regexp-in-string
             (format "\\(%s\\) *\n *\\(%s\\)" regexp regexp)
             "\\1\\2" string))
      ;; 删除粗体之前的空格
      (setq string
            (replace-regexp-in-string
             (format "\\(%s\\) +\\(<\\)" regexp)
             "\\1\\2" string))
      ;; 删除粗体之后的空格
      (setq string
            (replace-regexp-in-string
             (format "\\(>\\) +\\(%s\\)" regexp)
             "\\1\\2" string))
      string)))
```

**Comment by QiangF** [comment]
呵呵，我试试，不过我的elisp水平实在低的可怜。
如果可以那以后谢文章都不用latex了，我昨天才发现的一个小工具https://github.com/Zotero-ODF-Scan/zotero-odf-scan/

**Comment by QiangF** [comment]
你给的修改不行，换行还是空格。

**Comment by tumashu** [comment]
odt 估计需要单独处理

**Comment by QiangF** [comment]
搞混了，你的修改很好很成功！

**Comment by tumashu** [comment]
我已经更新了，你不用自己维护上面的代码了
